select * from customer


--1.What is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount) as Total_Revenue from customer group by gender

--2.Which customer used a discount but still spent more the average purchase amount?
select customer_id,purchase_amount from customer where purchase_amount>
(select avg(purchase_amount) from customer where discount_applied='yes')

--OR
select customer_id,purchase_amount from customer where discount_applied = 'Yes' 
and purchase_amount>(select avg(purchase_amount) from customer)

--3.Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(avg(review_rating),2) as Avg_review_rating from customer
group by item_purchased
order by avg(review_rating) desc

--4.compare the avg purchase amount between standard and average shipping
select shipping_type,avg(purchase_amount) from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5.Do subscribed customers spend more?compare average spend and total revenue 
--between subscribers and non-subscribers?

select* from customer

select subscription_status,count(customer_id),sum(purchase_amount) as Total_revenue,
avg(purchase_amount) as Avg_spend
from customer
group by subscription_status

--6.Which 5 products has the highest percentange of purchases with discounts applied?
select top 5 item_purchased,100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*)
as percentage
from customer
group by item_purchased
order by percentage desc

/*7.segment customers into New,Returning,loyal based on their total no.of previous purchases
and show the count of the segment*/
with customer_type as (
select customer_id,previous_purchases,
case 
    when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)
select customer_segment,count(*) as No_of_customers
from customer_type
group by customer_segment

--8.what are top 3 most purchased products within each category?
select * from (
select category,item_purchased,count(*) as purchase_count,
row_number() over (partition by category order by count(*) desc) as row_num
from customer
group by category,item_purchased
)t
where row_num<=3

--9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repear_buyers
from customer
where previous_purchases>5
group by subscription_status

--10.what is the revenue contribution of each age group
select * from customer

select age_group,sum(purchase_amount) as Total_revenue from customer
group by age_group
order by total_revenue desc